import { products, Product } from '../db';
import { merchantPolicies } from './rules';

export interface EvaluationResult {
  isValid: boolean;
  rejectReason?: string;
  margin: number;
  finalPrice: number;
  customerValue: number;
  merchantCost: number;
  includedAddons: Product[];
}

export function validateCandidate(candidate: any): EvaluationResult {
  const mainProduct = products.get(candidate.mainProductId);
  
  if (!mainProduct) {
    return { isValid: false, rejectReason: "Invalid main product ID", margin: 0, finalPrice: 0, customerValue: 0, merchantCost: 0, includedAddons: [] };
  }

  const includedAddons: Product[] = [];
  for (const addonId of candidate.addonIds || []) {
      const p = products.get(addonId);
      if (p) includedAddons.push(p);
  }

  if (includedAddons.length > merchantPolicies.global.max_bundle_items) {
      return { isValid: false, rejectReason: `Max bundle limit exceeded (${merchantPolicies.global.max_bundle_items})`, margin: 0, finalPrice: 0, customerValue: 0, merchantCost: 0, includedAddons };
  }

  let totalMerchantCost = mainProduct.cost;
  let totalCustomerValue = mainProduct.price || 0;

  for (const addon of includedAddons) {
      totalMerchantCost += addon.cost;
      totalCustomerValue += (addon.customerValue || addon.price || 0);
  }

  // SECURITY LAYER: Ensure offeredPrice is a strict number. 
  // If the LLM returned a string like "150,000", parse it safely.
  let parsedPrice = candidate.offeredPrice;
  if (typeof parsedPrice === 'string') {
      parsedPrice = parseInt(parsedPrice.replace(/,/g, ''), 10);
  }
  
  if (isNaN(parsedPrice) || parsedPrice <= 0) {
      return { isValid: false, rejectReason: "Malformed or invalid price generated by AI", margin: 0, finalPrice: 0, customerValue: 0, merchantCost: 0, includedAddons };
  }

  const expectedMargin = parsedPrice - totalMerchantCost;

  if (expectedMargin < merchantPolicies.global.min_gross_margin) {
      return { 
        isValid: false, 
        rejectReason: `Margin ₹${expectedMargin} < required ₹${merchantPolicies.global.min_gross_margin}`, 
        margin: expectedMargin, 
        finalPrice: parsedPrice, 
        customerValue: totalCustomerValue, 
        merchantCost: totalMerchantCost, 
        includedAddons 
      };
  }

  return {
      isValid: true,
      margin: expectedMargin,
      finalPrice: parsedPrice,
      customerValue: totalCustomerValue,
      merchantCost: totalMerchantCost,
      includedAddons
  };
}
